sudo: false

language: node_js

node_js:
  - "0.5.1"
  - "0.5"
  - "0.6.0"
  - "0.6"
  - "0.8.0"
  - "0.8"
  - "0.10.0"
  - "0.10"
  - "0.12.0"
  - "0.12"
  - "1.0.0"
  - "1"
  - "2.0.0"
  - "2"
  - "3.0.0"
  - "3"
  - "4.0.0"
  - "4"
  - "5.0.0"
  - "5"
  - "6.0.0"
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test

# Necessary to compile native modules for io.js v3 or Node.js v4
env:
  - CXX=g++-4.8

# Necessary to compile native modules for io.js v3 or Node.js v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
